app:
  env: dev

server:
  port: 8080

cors:
  allowOrigins:
    - "http://localhost:3000"
    - "http://localhost:8000"
  allowMethods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowHeaders:
    - "Origin"
    - "Content-Type"
    - "Accept"
  exposeHeaders:
    - "Content-Length"
    - "Content-Type"
  allowCredentials: false

db:
  type: postgres
  dsn: "postgres://lcasa:734826@localhost:5432/dnd_db?sslmode=disable"