// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Lucas Casagrande",
            "url": "http://github.com/Casagrande-Lucas",
            "email": "dev.casagrande@gmail.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/races": {
            "get": {
                "description": "Return all registered races",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Races"
                ],
                "summary": "List all races",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Race"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperror.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "httperror.ErrorResponse": {
            "type": "object",
            "properties": {
                "error_code": {
                    "type": "string"
                },
                "error_message": {
                    "type": "string"
                }
            }
        },
        "models.AbilityScoreBonuses": {
            "type": "object",
            "properties": {
                "charisma": {
                    "type": "integer"
                },
                "constitution": {
                    "type": "integer"
                },
                "dexterity": {
                    "type": "integer"
                },
                "intelligence": {
                    "type": "integer"
                },
                "strength": {
                    "type": "integer"
                },
                "wisdom": {
                    "type": "integer"
                }
            }
        },
        "models.Age": {
            "type": "object",
            "properties": {
                "average_lifespan": {
                    "type": "string"
                },
                "maximum_age": {
                    "type": "integer"
                },
                "minimum_age": {
                    "type": "integer"
                },
                "race_id": {
                    "type": "integer"
                }
            }
        },
        "models.Language": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.Proficiency": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.Race": {
            "type": "object",
            "properties": {
                "ability_score_bonuses": {
                    "$ref": "#/definitions/models.AbilityScoreBonuses"
                },
                "age": {
                    "$ref": "#/definitions/models.Age"
                },
                "alignment": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "languages_known": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Language"
                    }
                },
                "name": {
                    "type": "string"
                },
                "proficiencies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Proficiency"
                    }
                },
                "size": {
                    "type": "string"
                },
                "speed": {
                    "type": "integer"
                },
                "subraces": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Subrace"
                    }
                },
                "traits": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Trait"
                    }
                }
            }
        },
        "models.Subrace": {
            "type": "object",
            "properties": {
                "ability_score_bonuses": {
                    "$ref": "#/definitions/models.AbilityScoreBonuses"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "race_id": {
                    "type": "integer"
                }
            }
        },
        "models.Trait": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "D&D 5e API",
	Description:      "API D&D 5e card game.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
